<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241111082251 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE goal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(255) NOT NULL, parent_uuid UUID DEFAULT NULL, level VARCHAR(255) NOT NULL, status VARCHAR(15) NOT NULL, importance INT DEFAULT NULL, is_main BOOLEAN DEFAULT NULL, is_express BOOLEAN DEFAULT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, week INT DEFAULT NULL, quarter INT DEFAULT NULL, type_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_FCDCEB2EC54C8C93 ON goal (type_id)');
        $this->addSql('CREATE TABLE goal_type (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uuid UUID NOT NULL, name VARCHAR(100) NOT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE goal ADD CONSTRAINT FK_FCDCEB2EC54C8C93 FOREIGN KEY (type_id) REFERENCES goal_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT FK_FCDCEB2EC54C8C93');
        $this->addSql('DROP TABLE goal');
        $this->addSql('DROP TABLE goal_type');
    }
}
