<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20241111091108 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE goal DROP CONSTRAINT goal_pkey');
        $this->addSql('ALTER TABLE goal ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE goal ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE goal DROP id');
        $this->addSql('ALTER TABLE goal ADD PRIMARY KEY (uuid)');
        $this->addSql('ALTER TABLE goal_type ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
        $this->addSql('ALTER TABLE goal_type ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE goal_type DROP created_at');
        $this->addSql('ALTER TABLE goal_type DROP updated_at');
        $this->addSql('DROP INDEX goal_pkey');
        $this->addSql('ALTER TABLE goal ADD id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        $this->addSql('ALTER TABLE goal DROP created_at');
        $this->addSql('ALTER TABLE goal DROP updated_at');
        $this->addSql('ALTER TABLE goal ADD PRIMARY KEY (id)');
    }
}
